### PR TITLE
chore(general): Remove profile pictures visibility options

### LINKED ISSUE #7609: Remove profile picture visibility options
# Bug Report

## Description

When the new account is created, "everyone" option is set for both cases (https://github.com/status-im/status-desktop/issues/7310). Additionally, the entire config section should be removed and application shouldn't distinguish between visibility modes. In every case we assume that the user wants to see avatars.

It solves some other issues related to avatar's visibility:
https://github.com/status-im/status-desktop/issues/6303
https://github.com/status-im/status-desktop/issues/6301
https://github.com/status-im/status-desktop/issues/7311

Probably logic introduced here is no longer needed:
https://github.com/status-im/status-desktop/issues/7309

Screenshot from 2022-09-27 12-47-21

#### Expected behavior

Profile picture should be displayed always when available

#### Actual behavior

Profile picture visibility in the application tries to follow settings.

### Additional Information

- Status desktop version:
- Operating System:

### PR DESCRIPTION
**Pull request by micieslak**
### What does the PR do

From now on, if the image is available it should be displayed uncoditionally.

Closes: #7609

Related to: https://github.com/status-im/status-desktop/pull/7432, https://github.com/status-im/status-desktop/issues/7310

### Affected areas
`Settings` -> `Messaging`

### Screenshot of functionality (including design for comparison)

Screenshot from 2022-10-06 22-03-21

### CODE REVIEW

**Review by caybro — APPROVED** [review]

**Review by saledjenic — APPROVED** [review]
@micieslak this is not needed as a feature any more?

**Comment by micieslak** [comment]
> @micieslak this is not needed as a feature any more?

Exactly. I had some questions to @John-44 about profile pictures visibility and it turned out that currently we always want to display profile pictures. And it causes that those options are not needed at all.

**Comment by micieslak** [comment]
@elina2015 Could you please take a look? Merging that would close many issues :)

**Comment by caybro** [comment]
@micieslak needs rebase

**Pull request merged**
