### PR TITLE
fix(@desktop/chat): Fix moving channels between categories

### LINKED ISSUE #7422: Channel moved in/out from Community category via Edit category is not reflected for other members
### Description

Steps:
1. Create community with some channels
2. Move a part of channels to category.
3. Edit category and add or remove a channel.

Result : other members of community dont update their channels list.

Expected : changes made by admin in channels and categories must be reflected in their list

https://user-images.githubusercontent.com/6445843/190865687-daeef9a6-fa5b-4e8b-93fc-e7948ed54e18.mp4

Notes:
Possibly the issue is in missing logic for updating category channels in function `proc handleCommunityUpdates` in file `src/app_service/service/community/service.nim`. In else block after comment `# but something is different` the name and position change is handled only.

### PR DESCRIPTION
**Pull request by endulab**
Fix #7422

### What does the PR do

Fixes reordering channels for community members.

### Affected areas

Community, channels list, channel categories

### Screenshot of functionality (including design for comparison)

https://user-images.githubusercontent.com/61889657/193846742-79ff9774-250b-4fba-849d-4ee1919b8a66.mov

### CODE REVIEW

**Comment by endulab** [comment]
@elina2015 can you play a bit with channel categories ?

**Review by elina2015 — CHANGES_REQUESTED** [review]
@endulab hey, the members of the community can still see (but cannot write) the deleted channels - I sign out snd sign in few times, but the issue is still shown.
image
Could you kindly check?

**Comment by endulab** [comment]
@elina2015 I finally has some time to take a look at the issue. Unfortunately, the propagation of deleting channel is not correct. This should be a separated issue. I will test more on master branch and create a ticket for this. 
What should work correctly in this ticket:
- moving channels inside a category
- moving channels between categories

https://user-images.githubusercontent.com/61889657/197160196-434cfd29-8af8-48ca-ab2b-decea176cd8e.mov

**Review by borismelnik — APPROVED** [review]
LGTM

**Comment by elina2015** [comment]
@endulab hey, thank you for your comment! I still observe the issues about moving the channels between categories:
Member:
image
Owner:
image
Could you kindly check?

**Review by elina2015 — CHANGES_REQUESTED** [review]
Found an issue

**Review by elina2015 — APPROVED** [review]
Tested and approved

**Review by osmaczko — APPROVED** [review]

**Pull request merged**
