### PR TITLE
feat: encrypt communities

### LINKED ISSUE #7446: Add option to create encrypted community
As a user
I want to be able to create an encrypted community
So that I can make sure nobody who's not a member can read the messages

### Description

We just added support for encrypted communities, the user should be presented with a checkbox that allows to enable encryption when creating the community.

https://github.com/status-im/status-go/blob/eb4ab9316cc0f0ba07b01b4177bd50bdfc3ae33a/protocol/requests/create_community_request.go#L46 can be set to `true` if the checkbox is enabled.

Only communities with a concept of membership should have this option (regardless of whether is manual or automatic approval)

### PR DESCRIPTION
**Pull request by richard-ramos**
Fixes: #7446 
Requires:
- https://github.com/status-im/status-go/pull/2899

Note: encryption wasn't added to imported discord communities

### CODE REVIEW

**Review by 0x-r4bbit — CHANGES_REQUESTED** [review]
This LGTM, but we need the same flag for `requestImportDiscordCommunity` as well.
That function is almost identical to `createCommunity` and also expectes a CreateCommunityRequest object.

So should be enough to just pass the flag to the API

**Review by stefandunca — APPROVED** [review]

**Comment by elina2015** [comment]
@richard-ramos I created a community with encryption and accepted a request for joining from another user. This new member tries to send a message in the encrypted community, but instead of sending the message only the loader is shown infinitely.  Could you kindly check?

**Review by elina2015 — CHANGES_REQUESTED** [review]
@richard-ramos I created a community with encryption and accepted a request for joining from another user. This new member tries to send a message in the encrypted community, but instead of sending the message, only the loader is shown infinitely.  Could you kindly check?

**Comment by PascalPrecht** [comment]
This is most likely related to some things that needed fixing and are pending here: https://github.com/status-im/status-go/pull/2876

**Comment by richard-ramos** [comment]
@elina2015 I updated the status-go version this PR is pointing to, to the latest version. Hopefully the problem you reported is fixed there!

**Review by 0x-r4bbit — CHANGES_REQUESTED** [review]
I don't want to be annoying, but it seems that the `encrypted` parameter is missing here https://github.com/status-im/status-desktop/pull/7829/files#diff-58809306e27370b2357e933615a3d14f4f5f98dd124c13064accbb34b0835f32R149

**Comment by PascalPrecht** [comment]
@richard-ramos FYI I've fixed the spot I've mentioned and rebased this PR, so make sure you reset your local one to this hash here.

Will test this now

**Review by 0x-r4bbit — APPROVED** [review]

**Review by elina2015 — APPROVED** [review]
Tested and approved

**Pull request merged**
